spring:
  #rabbitmq
  rabbitmq:
    username: root
    password: root123
    port: 5672
    virtual-host: /
    host: 192.168.0.111
    publisher-confirms: true
    listener:
      simple:
        acknowledge-mode: manual #采用手动应答
        concurrency: 1 #指定最小的消费者数量
        max-concurrency: 10 #指定最大的消费者数量
        retry:
          enabled: true #是否支持重试

